### ISSUE TITLE
最后一步报错，请求帮助！

### ISSUE THREAD

**Issue by Wygdbb** [yeskn-studio/vmoex-framework#36]
- 运行环境: 阿里云ESC

```
1.MySQL 5.7
2.PHP-7.3
3.Redis 5.0.8
4.Nginx 1.17.5
```

- 报错命令部分
> 之前的命令都是没有报错的，而且 php bin/console server:run 0.0.0.0:8000 也没有报错。

```

root@iZbp11ugrf9k59wexhyoheZ:~/vmoex-framework# php bin/push-service.php start -d


Workerman[bin/push-service.php] start in DAEMON mode
pcntl_fork() has been disabled for security reasons in file /root/vmoex-framework/vendor/workerman/workerman/Worker.php on line 1123
PHP Fatal error:  Uncaught Exception: setsid fail in /root/vmoex-framework/vendor/workerman/workerman/Worker.php:1130
Stack trace:
#0 /root/vmoex-framework/vendor/workerman/workerman/Worker.php(502): Workerman\Worker::daemonize()
#1 /root/vmoex-framework/bin/push-service.php(156): Workerman\Worker::runAll()
#2 {main}
  thrown in /root/vmoex-framework/vendor/workerman/workerman/Worker.php on line 1130

Fatal error: Uncaught Exception: setsid fail in /root/vmoex-framework/vendor/workerman/workerman/Worker.php:1130
Stack trace:
#0 /root/vmoex-framework/vendor/workerman/workerman/Worker.php(502): Workerman\Worker::daemonize()
#1 /root/vmoex-framework/bin/push-service.php(156): Workerman\Worker::runAll()
#2 {main}
  thrown in /root/vmoex-framework/vendor/workerman/workerman/Worker.php on line 1130

```

- 日志
> 看日志像是**php7.3版本**过高导致的？

```
root@iZbp11ugrf9k59wexhyoheZ:~/vmoex-framework/var/logs# cat prod-2020-05-10.log 
[2020-05-10 13:30:15] php.INFO: User Deprecated: The "assetic.asset_manager" service is private, getting it from the container is deprecated since Symfony 3.2 and will fail in 4.0. You should either make the service public, or stop using the container directly and use dependency injection instead. {"exception":"[object] (ErrorException(code: 0): User Deprecated: The \"assetic.asset_manager\" service is private, getting it from the container is deprecated since Symfony 3.2 and will fail in 4.0. You should either make the service public, or stop using the container directly and use dependency injection instead. at /root/vmoex-framework/vendor/symfony/symfony/src/Symfony/Component/DependencyInjection/Container.php:282)"} []
[2020-05-10 13:30:15] php.INFO: User Deprecated: Using the "Twig_Source" class is deprecated since Twig version 2.7, use "Twig\Source" instead. {"exception":"[object] (ErrorException(code: 0): User Deprecated: Using the \"Twig_Source\" class is deprecated since Twig version 2.7, use \"Twig\\Source\" instead. at /root/vmoex-framework/vendor/twig/twig/lib/Twig/Source.php:7)"} []
[2020-05-10 13:30:15] assetic.ERROR: The template "SecurityBundle:Collector:security.html.twig" contains an error: Unknown "profiler_dump" function in "SecurityBundle:Collector:security.html.twig" at line 116. [] []
[2020-05-10 13:30:15] assetic.ERROR: The template "DoctrineBundle:Collector:db.html.twig" contains an error: Unknown "profiler_dump" function in "DoctrineBundle:Collector:db.html.twig" at line 243. [] []
[2020-05-10 13:30:15] php.INFO: User Deprecated: The Symfony\Component\Process\ProcessBuilder class is deprecated since Symfony 3.4 and will be removed in 4.0. Use the Process class instead. {"exception":"[object] (ErrorException(code: 0): User Deprecated: The Symfony\\Component\\Process\\ProcessBuilder class is deprecated since Symfony 3.4 and will be removed in 4.0. Use the Process class instead. at /root/vmoex-framework/vendor/symfony/symfony/src/Symfony/Component/Process/ProcessBuilder.php:14)"} []
root@iZbp11ugrf9k59wexhyoheZ:~/vmoex-framework/var/logs# 

```

**Comment by Jaggle** [comment]
你的报错信息已经提示错误原因了，请谷歌搜索`pcntl_fork() has been disabled for security reasons`，第一条就是。
